stages:
  - build
  - package
  - deploy

build_app:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: build
  script:
    - ant
  artifacts:
    paths:
      - build/*.xar

build_dev:
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose build --pull
    - docker-compose push
  only:
    - develop
  except:
    - tags

deploy_dev:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: deploy
  environment:
    name: test
  script:
    - which ssh-agent
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PRIVATE_KEY")
    - scp docker-compose.yml $SSH_USER@$SSH_IP:~/docker-compose.yml
    - ssh $SSH_USER@$SSH_IP "docker-compose pull && docker-compose down && docker-compose up -d"
