stages:
  - build
  - package
  - deploy_docker
  - deploy_app
  - release

# templates:
.ssh-config: &ssh
- which ssh-agent
- eval $(ssh-agent -s)
- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh

.env: &env
- echo $SECRETS >> docker/ahikar.env
- sh docker/set-env-for-docker-compose.sh

# used for develop and master, see test for all other cases!
.deploy: &deploy
- scp -o 'StrictHostKeyChecking no' docker/ahikar.env $SSH_USER@$SSH_IP:~/$CI_COMMIT_REF_NAME/ahikar.env
- scp -o 'StrictHostKeyChecking no' docker/tg.env $SSH_USER@$SSH_IP:~/$CI_COMMIT_REF_NAME/tg.env
- scp -o 'StrictHostKeyChecking no' docker/docker-compose.yml $SSH_USER@$SSH_IP:~/$CI_COMMIT_REF_NAME/docker-compose.yml
- scp -o 'StrictHostKeyChecking no' docker/.env $SSH_USER@$SSH_IP:~/$CI_COMMIT_REF_NAME/.env
- ssh -o 'StrictHostKeyChecking no' $SSH_USER@$SSH_IP "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
- ssh -o 'StrictHostKeyChecking no' $SSH_USER@$SSH_IP "cd ~/$CI_COMMIT_REF_NAME; docker-compose pull && docker-compose down && docker-compose up -d"

build_exist_app-all:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: build
  script:
    - cd exist-app
    - ant -propertyfile ${CI_COMMIT_REF_NAME}.build.properties prepare
    - FILENAME=$(ls build/ahikar*.xar)
    - curl -u ci:${EXIST_UPLOAD_PW} -X POST -F file=@${FILENAME} https://ci.de.dariah.eu/exist-upload
  artifacts:
    paths:
      - exist-app/build/*.xar

load_frontend-all:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: build
  variables:
    FRONTEND_REPO_ID: "9882"
  script:
    - 'curl --output frontend.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$CI_API_V4_URL/projects/$FRONTEND_REPO_ID/jobs/artifacts/develop/download?job=build"'
    - unzip frontend.zip
    - mkdir frontend
    - mv Qviewer/dist/* frontend/
  artifacts:
    paths:
      - frontend/

build_docker-all:
  image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/ci-docker
  services:
    - docker:dind
  stage: package
  script:
    - *ssh
    - *env
    - mv frontend/ docker/frontend
    - cd docker
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose build --pull
    # - docker-compose up & sleep 30s &&
    # like to add a test here, but seems that within the runner specified port is not available.
    # - while ! curl --silent --head http://localhost:8094/db/ | grep "200 OK"; do sleep 2s; echo "test failed"; curl --head http://localhost:8094/db/; done
    # - docker-compose down
    - docker-compose push
  except:
    - tags
  timeout: 5m

deploy_docker-test:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: deploy_docker
  except:
    - master
    - develop
    - tags
  environment:
    name: testing
  script:
    - *ssh
    - *env
    - scp -o 'StrictHostKeyChecking no' docker/ahikar.env $SSH_USER@$SSH_IP:~/ahikar.env
    - scp -o 'StrictHostKeyChecking no' docker/tg.env $SSH_USER@$SSH_IP:~/tg.env
    - scp -o 'StrictHostKeyChecking no' docker/docker-compose.yml $SSH_USER@$SSH_IP:~/docker-compose.yml
    - scp -o 'StrictHostKeyChecking no' docker/.env $SSH_USER@$SSH_IP:~/.env
    - ssh -o 'StrictHostKeyChecking no' $SSH_USER@$SSH_IP "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
    - ssh -o 'StrictHostKeyChecking no' $SSH_USER@$SSH_IP "docker-compose pull && docker-compose down && docker-compose up -d"

deploy_docker-dev:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: deploy_docker
  only:
    - develop
  environment:
    name: ahikar-dev
  script:
    - *ssh
    - *env
    - *deploy

deploy_docker-master:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: deploy_docker
  only:
    - master
  environment:
    name: ahikar
  script:
    - *ssh
    - *env
    - *deploy

deploy_app-test:
  image: curlimages/curl
  stage: deploy_app
  except:
    - master
    - develop
    - tags
  environment:
    name: ahikar-test
  script:
    - curl --get --silent https://ahikar-test.sub.uni-goettingen.de/api/deploy

deploy_app-dev:
  image: curlimages/curl
  stage: deploy_app
  only:
    - develop
  environment:
    name: ahikar-dev
  script:
    - curl --get --silent https://ahikar-dev.sub.uni-goettingen.de/api/deploy

deploy_app-master:
  image: curlimages/curl
  stage: deploy_app
  only:
    - master
    - tags
  environment:
    name: ahikar
  script:
    - curl --get --silent https://ahikar.sub.uni-goettingen.de/api/deploy

# when a git flow release is made, a tag will be pushed starting this job. it
# will keep the resulting artifact from job number one and it will set up a
# Gitlab release at the repo. therefore the merge message starting at the release
# branch should be written in markdown.
.release:
  stage: release
  only:
    - tags
  script:
    # get number of first job in pipeline (assuming that this will create the needed artifact)
    # it is also possible to query for a job name by altering the jq filter
    - 'curl --output jobs.json --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/jobs"'
    - CI_JOB_TARGET=$(jq ".[0].id" < jobs.json)
    - echo $CI_JOB_TARGET
    # keep artifact (release will link there)
    - 'curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/$CI_JOB_TARGET/artifacts/keep"'
    # create release data
    # parse commit message (markdown, lines starting with “\”)
    - MARKDOWN=$(echo "$CI_COMMIT_MESSAGE" | sed 's=^\\==g')
    # prepare the json file
    - 'jq
      ".name = \"$CI_PROJECT_PATH $CI_COMMIT_TAG\" |
      .tag_name = \"$CI_COMMIT_TAG\" |
      .description = \"$MARKDOWN\" |
      .assets.links[0].name = \"package\" |
      .assets.links[0].url = \"https://gitlab.gwdg.de/$CI_PROJECT_PATH/-/jobs/$CI_JOB_TARGET/artifacts/download\"
      " < .gitlab/gitlab-release.json.tmpl > gitlab-release.json'
    - 'curl --header "Content-Type: application/json" --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --data @gitlab-release.json --request POST $CI_API_V4_URL/projects/$CI_PROJECT_ID/releases'
  artifacts:
    paths:
      - gitlab-release.json
