image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - 'which ssh-agent || ( apk add --update openssh-client )'
  - apk add --update bash
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - bash -c 'ssh-add <(echo "$PRIVATE_KEY")'

build_dev:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:CI_COMMIT_REF_NAME"
  only:
    - develop
  except:
    - tags

deploy_dev:
  stage: deploy
  environment:
    name: develop
  only:
    - master
  except:
    - tags
  script:
    - ssh $DEV_SERVER_USER@$DEV_HOSTNAME "cd $DEV_SERVER_DIRECTORY && docker-compose pull && docker-compose stop web && docker-compose up -d"
