image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

# before_script:
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  - 'which ssh-agent || ( apk add --update openssh-client )'
#  - apk add --update bash
#  - mkdir -p ~/.ssh
#  - eval $(ssh-agent -s)
#  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'

build_app:
  image: docker.gitlab.gwdg.de/fontane-notizbuecher/build:latest
  stage: build
  script:
    - ant
  artifacts:
    paths:
      - build/*.xar

build_dev:
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose build --pull
    - docker-compose push
  only:
    - develop
  except:
    - tags

.deploy_dev:
  stage: deploy
  environment:
    name: develop
  only:
    - master
  except:
    - tags
  script:
    - ssh $DEV_SERVER_USER@$DEV_HOSTNAME "cd $DEV_SERVER_DIRECTORY && docker-compose pull && docker-compose stop web && docker-compose up -d"
