version: '3'
services:
  existdb:
    image: existdb/existdb
    expose:
      - "8080"
    restart: unless-stopped
  httpd:
    image: httpd
    ports:
      - "9082:80"
    volumes:
      - ./httpd/vhosts:/usr/local/apache2/conf/sites
    restart: unless-stopped
