version: '3'
services:
  existdb:
    build:
      context: .
      dockerfile: Dockerfile-exist
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/existdb:develop
    expose:
      - "8080"
    restart: unless-stopped
  httpd:
    build:
      context: .
      dockerfile: Dockerfile-httpd
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/httpd:develop
    ports:
      - "8094:80"
    volumes:
      - ./httpd/vhosts:/usr/local/apache2/conf/sites
    restart: unless-stopped
