version: '3'
services:
  existdb:
    build:
      context: ..
      dockerfile: docker/Dockerfile-exist
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/existdb:develop
    ports:
      - "9094:8080"
    restart: unless-stopped
    env_file:
      - ahikar.env
      - tg.env
    volumes:
      - /tmp:/tmp:z

  httpd:
    build:
      context: .
      dockerfile: Dockerfile-httpd
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/httpd:develop
    ports:
      - "8094:80"
    restart: unless-stopped
