version: '3'
services:
  existdb:
    build:
      context: ..
      dockerfile: docker/Dockerfile-exist
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/existdb:develop
    entrypoint:
      - java
      - -javaagent:/prometheus/jmx_prometheus_javaagent-0.12.0.jar=8079:/prometheus/jmx_prometheus_config.yaml
      - org.exist.start.Main
      - jetty
    ports:
      - "8080"
    restart: unless-stopped
    env_file:
      - ahikar.env
      - tg.env
    volumes:
      - ./exist/data:/exist/data:z
      - ./exist/logs:/exist/logs:z
      - ./prometheus:/prometheus:z

  httpd:
    build:
      context: .
      dockerfile: Dockerfile-httpd
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/httpd:develop
    ports:
      - "${PORT}:80"
    restart: unless-stopped

  httpd-prometheus:
    # can be built with the submodule "apache_exporter" integrated here.
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/apache-prometheus:latest
    entrypoint:
      - /bin/apache_exporter
      - --scrape_uri=http://httpd/server-status/?auto
    ports:
      - "9117"
