FROM existdb/existdb:release

# copy EXPath packages
COPY exist-app/build/*.xar /exist/autodeploy/
COPY exist-app/build/dependencies/*.xar /exist/autodeploy/

# copy custom config, e.g. to enable scheduled jobs
# COPY docker/exist_conf.xml /exist/etc/conf.xml