version: '3'
services:
  existdb:
    build:
      context: ..
      dockerfile: docker/Dockerfile-exist
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/existdb:develop
    ports:
      - "9094:8080"
    restart: unless-stopped
    env_file:
      - ahikar.env
      - tg.env
    volumes:
      - ./exist/data:/exist/data:z
      - ./exist/logs:/exist/logs:z

  httpd:
    build:
      context: .
      args:
        # args are used to get static data from a non-public git repo.
        - gitlabuser
        - gitlabpass
      dockerfile: Dockerfile-httpd
    image: docker.gitlab.gwdg.de/subugoe/ahiqar/backend/httpd:develop
    ports:
      - "8094:80"
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/local/apache2/htdocs:z
