# this config file defines the tests that check if the TextAPI is available
# after the redeployment of the application. the tests only pass if an HTTP
# request to the TextAPI returns a status code 200.

# Templates
.job_definition: &job_definition
  image: docker.gitlab.gwdg.de/mrodzis/test
  stage: api_tests
  dependencies: []

.check_HTTP_status: &check_HTTP_status
  - status=$(echo $header | head -n 1 | cut -d" " -f 2)
  - echo "Current HTTP status is $status."
  - if [[ "$status" == "200" ]]; then exit 0; else exit 1; fi

test_api_status-test:
  <<: *job_definition
  except:
    - main
    - tags
    - develop
  script:
    - header=$(curl --head -s https://ahikar-test.sub.uni-goettingen.de/api/textapi/ahikar/arabic-karshuni/collection.json)
    - *check_HTTP_status

test_api_status-develop:
  <<: *job_definition
  only:
    - develop
  script: 
    - header=$(curl --head -s https://ahikar-dev.sub.uni-goettingen.de/api/textapi/ahikar/arabic-karshuni/collection.json)
    - *check_HTTP_status

test_api_status-main:
  <<: *job_definition
  only:
    - main
  script: 
    - header=$(curl --head -s https://ahikar.sub.uni-goettingen.de/api/textapi/ahikar/arabic-karshuni/collection.json)
    - *check_HTTP_status
  retry: 2
